[metadata]
name = pyynl
author = Donald Hunter
author_email = donald.hunter@gmail.com
description = yaml netlink (ynl)
version = 0.0.1

[options]
packages =
    pyynl
    pyynl.lib
python_requires = >=3.9
install_requires =
    jsonschema
    pyyaml

[options.entry_points]
console_scripts =
    ynl = pyynl.cli:main
    ynl-ethtool = pyynl.ethtool:main
